
module.exports = {
  singleQuote: '\''.charCodeAt(0),
  doubleQuote: '"'.charCodeAt(0),
  backslash: '\\'.charCodeAt(0),
  backTick: '`'.charCodeAt(0),
  slash: '/'.charCodeAt(0),
  newline: '\n'.charCodeAt(0),
  space: ' '.charCodeAt(0),
  feed: '\f'.charCodeAt(0),
  tab: '\t'.charCodeAt(0),
  carriageReturn: '\r'.charCodeAt(0),
  openedParenthesis: '('.charCodeAt(0),
  closedParenthesis: ')'.charCodeAt(0),
  openedCurlyBracket: '{'.charCodeAt(0),
  closedCurlyBracket: '}'.charCodeAt(0),
  openSquareBracket: '['.charCodeAt(0),
  closeSquareBracket: ']'.charCodeAt(0),
  semicolon: ';'.charCodeAt(0),
  asterisk: '*'.charCodeAt(0),
  colon: ':'.charCodeAt(0),
  comma: ','.charCodeAt(0),
  dot: '.'.charCodeAt(0),
  atRule: '@'.charCodeAt(0),
  tilde: '~'.charCodeAt(0),
  hash: '#'.charCodeAt(0),

  atEndPattern: /[ \n\t\r\f\{\(\)'"\\,/\[\]#!]/g,
  wordEndPattern: /[ \n\t\r\f\(\)\{\}:,,@!'"\\\]\[#]|\/(?=\*)/g,
  badBracketPattern: /.[\\\/\("'\n]/,

  pageSelectorPattern: /^@page[^\w-]+/,
  variableSpaceColonPattern: /^\s*:/,
  variablePattern: /^@[^:\(\{]+:/,
  hashColorPattern: /^#[0-9a-fA-F]{6}$|^#[0-9a-fA-F]{3}$/
};
